version: '2'
services:
    bot:
      env_file:
        - .env
      build: ./
      image: minizinger/kuubio
      container_name: "bot"
      restart: always
      volumes:
        - ./db/:/db/
      command: python3 bot.py
