version: '2'
services:
    bot:
      env_file:
        - .env
      build: ./bot
      image: minizinger/kuubio
      container_name: "bot"
      links:
        - mongo
      depends_on:
        - mongo
      volumes:
        - ./external_data:/external_data
        - ./pip_packages:/usr/local/lib/python3.6/site-packages
      command: python3 bot.py
    mongo:
        image: jixer/rpi-mongo
        container_name: "mongo"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet